sudo: required
services:
  - docker

before_install:
  - docker build -t brenotx/docker-react -f Dockerfile.dev .

script:
  - docker run brenotx/docker-react npm run test -- --coverage

deploy: # AWS app configs.
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-019059528798"
  bucket_path: "docker-react"
  on: # Any time we push code to branch master we should deploy.
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access-key:
    secure: "$AWS_SECRET_ACCESS_KEY"
